### PR TITLE
docs: Fix sign in definition of CURVE.n

### PR DESCRIPTION
**Pull request by dsernst**
Fixes docs to correctly describe sign in Group Order definition (`CURVE.n`) to be `+`, not `-`.

Code was correct:
https://github.com/paulmillr/noble-ed25519/blob/ee83b99d808a685f8cb842954f50830f4b940a9e/index.ts#L31

Also matches standard as described elsewhere like RFC 8032.

### CODE REVIEW

**Comment by dsernst** [comment]
Not a big deal but do also want to note my confusion on why you call this value `n`.

DJB's Ed25519 paper (https://ed25519.cr.yp.to/ed25519-20110926.pdf) and Wikipedia both call cursive `l` (https://en.wikipedia.org/wiki/EdDSA#Ed25519).

RFC 8032 calls it `q` (https://datatracker.ietf.org/doc/html/rfc8032#section-6)

**Comment by paulmillr** [comment]
@dsernst i've first developed secp256k1, and order was called n there. So i've copied for consistency. Do you know why everyone uses different symbols?

**Comment by dsernst** [comment]
> Do you know why everyone uses different symbols?

In my experience, cryptographers are *dreadful* at naming things :smile:. So many random letters, so many techniques named after people rather than what's happening. It's all way more obtuse than ideal.

That's one thing that made your library stand out... you've done a great job keeping it reasonable, simple as possible, clean, etc. Breath of fresh air.

**Comment by dsernst** [comment]
One of my favorite examples is the name "public key". It doesn't make any sense.
How can a "key" be public....? 🙃

Even worse because both `public key` and `private key` abbreviate to "pk", so lots of ambiguity.

Thankfully BTC etc are slowly moving people towards the terminology of "address", which is a lot more clear.

**Pull request merged**
