### PR TITLE
Support sign with publicKey.

### PR DESCRIPTION
**Pull request by robxyy**
In most cases, we sign after generating the KeyPair, so I added the public Key to the Sign method.

On my MBP,  the bench log:

```
sign x 1,867 ops/sec @ 535μs/op
signWithPublicKey x 3,214 ops/sec @ 311μs/op
```

### CODE REVIEW

**Comment by paulmillr** [comment]
That's pretty cool. Does the speedup really matter to you though? What is your use case?

**Comment by paulmillr** [comment]
I mean, i'm all for stuff like this, but it complicates api. Perhaps we could find a better solution.

**Comment by vae520283995** [comment]
```
export async function sign(hash: Hex, privateKey: Hex) {
  const privBytes = await utils.sha512(normalizePrivateKey(privateKey));
  const p = encodePrivate(privBytes);
  **const P = Point.BASE.multiply(p);**
  const msg = ensureBytes(hash);
  const r = await sha512ToNumberLE(keyPrefix(privBytes), msg);
  const R = Point.BASE.multiply(r);
  const h = await sha512ToNumberLE(R.toRawBytes(), P.toRawBytes(), msg);
  const S = mod(r + h * p, CURVE.n);
  const sig = new Signature(R, S);
  return typeof hash === 'string' ? sig.toHex() : sig.toRawBytes();
}
```
In the signature method, the public key is generated by the private key. For objects that store the public key externally, the public key is passed in when the signature method is called, then the step of generating the public key can be omitted, saving time

**Comment by paulmillr** [comment]
I understand, but my questions still require answers.

**Comment by vae520283995** [comment]
> I understand, but my questions still require answers. 

Maybe the author’s idea is simply to speed up the signature

**Comment by paulmillr** [comment]
Okay, in this case i'll prefer a new method, instead of adding an additional argument to sign(). I will think what could be an ideal API for that.

**Pull request closed without merging**
