### PR TITLE
Update mod.ts file to export etc

### PR DESCRIPTION
**Pull request by quentinadam**
I am suggesting the following minor changes :

- Export `etc` in mod.ts.
- Use the `export { ... } from '...'` syntax instead of `import {...} from '...'; export { ... }`

### CODE REVIEW

**Comment by paulmillr** [comment]
is mod.ts even needed? People can just use index.ts

**Comment by quentinadam** [comment]
It’s obviously not strictly needed but somewhat more conventional on Deno.

**Comment by paulmillr** [comment]
I don't remember why I did not do export in the first phase. It was probably related to types or something like that.

**Comment by paulmillr** [comment]
so we can merge this, but only the etc part; export needs to be reverted

**Comment by quentinadam** [comment]
I have reverted the export part.

**Pull request merged**
